name: Auto Update Dev Branch

on:
  push:
    branches:
      - dev
  schedule:
    - cron: '0 0 * * *'  # This will run daily at midnight UTC
  workflow_dispatch:  # This allows manual triggers

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: dev

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto Update Dev Branch"
          git push origin dev

      - name: Create Pull Request to main if dev is ahead
        if: success()
        run: |
          if [ $(git rev-list --count main..dev) -gt 0 ]; then
            gh pr create --base main --head dev --title "Merge dev into main" --body "This PR was automatically created by the Auto Update workflow."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

